"""Audit-ready PDF report generation."""
from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="Brand", fontSize=18, textColor=colors.HexColor("#6D28D9"), spaceAfter=6, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="Section", fontSize=12, textColor=colors.HexColor("#4C1D95"), spaceBefore=14, spaceAfter=6, fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="BodyText2", fontSize=10, leading=14, spaceAfter=4))
    return styles


def generate_complaint_pdf(data: dict[str, Any], report_type: str = "Complaint Report") -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    styles = _styles()
    story = []

    story.append(Paragraph("AIVOA Complaint Management System", styles["Brand"]))
    story.append(Paragraph(f"{report_type} — Audit Ready", styles["Heading2"]))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", styles["BodyText2"]))
    story.append(Spacer(1, 0.2 * inch))

    complaint_id = data.get("complaint_id") or data.get("id") or "DRAFT"
    story.append(Paragraph(f"Complaint ID: {complaint_id}", styles["Section"]))

    rows = [
        ["Field", "Value"],
        ["Customer", str(data.get("customer_name") or "—")],
        ["Source", str(data.get("complaint_source") or "—")],
        ["Email", str(data.get("email") or "—")],
        ["Phone", str(data.get("phone") or "—")],
        ["Country", str(data.get("country") or "—")],
        ["Product", str(data.get("product_name") or "—")],
        ["Strength", str(data.get("strength") or "—")],
        ["Dosage Form", str(data.get("dosage_form") or "—")],
        ["Batch Number", str(data.get("batch_number") or "—")],
        ["Mfg Date", str(data.get("manufacturing_date") or "—")],
        ["Expiry", str(data.get("expiry_date") or "—")],
        ["Quantity", str(data.get("quantity") or "—")],
        ["Status", str(data.get("status") or "pending")],
        ["Priority", str(data.get("priority") or "—")],
        ["Risk Level", str(data.get("risk_level") or "—")],
    ]
    table = Table(rows, colWidths=[2 * inch, 4.5 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#6D28D9")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E9D5FF")),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#FAF5FF")),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
                ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]
        )
    )
    story.append(table)

    story.append(Paragraph("Complaint Summary", styles["Section"]))
    story.append(Paragraph(str(data.get("summary") or "—"), styles["BodyText2"]))

    story.append(Paragraph("AI Suggested Investigation", styles["Section"]))
    for label, key in [
        ("Potential Issue", "potential_issue"),
        ("Root Cause", "possible_root_cause"),
        ("Suggested Test", "suggested_test"),
        ("Recommended Action", "recommended_action"),
        ("Regulatory Concern", "regulatory_concern"),
        ("Impact", "impact"),
        ("AI Reasoning", "ai_reasoning"),
    ]:
        val = data.get(key)
        if val:
            story.append(Paragraph(f"<b>{label}:</b> {val}", styles["BodyText2"]))

    if data.get("investigation"):
        inv = data["investigation"]
        story.append(Paragraph("Investigation Details", styles["Section"]))
        for key in ("summary", "root_cause_analysis", "risk_assessment", "recommended_capa", "preventive_actions", "timeline", "owner"):
            if inv.get(key):
                story.append(Paragraph(f"<b>{key.replace('_', ' ').title()}:</b> {inv[key]}", styles["BodyText2"]))

    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph("This document is generated by AIVOA for internal QA / audit use.", styles["BodyText2"]))

    doc.build(story)
    return buffer.getvalue()
